# Numpy Training Notebook

In [2]:
import numpy as np

#### Numpy ndarray basic attributes

In [3]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

print(f"type {type(data)}")
print(f"ndim {data.ndim}")
print(f"shape {data.shape}")
print(f"size {data.size}")
print(f"dtype {data.dtype}")
print(f"nbytes {data.nbytes}")

[[1 2]
 [3 4]
 [5 6]]
type <class 'numpy.ndarray'>
ndim 2
shape (3, 2)
size 6
dtype int64
nbytes 48


##### Create ndarrays with diferent types

In [4]:
data = np.array([1, 2, 3], dtype=int)
print(data)
data = np.array([1, 2, 3], dtype=float)
print(data)
print(np.array([1, 2, 3], dtype=complex))

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


#### Typecasting a numpy array

In [5]:
data = np.array([1, 2, 3], dtype=float)
print(data.dtype)
data = np.array(data, dtype=int)
print(data.dtype)

# or by using astype method of the ndarray class
print(data.astype(float).dtype)

float64
int64
float64


#### Promoting data types with numpy

In [6]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)

print((d1 + d2).dtype)

# np.sqrt(np.array([-1, 0, 1])) # shourd emit a warning
np.sqrt(np.array([-1, 0, 1], dtype=complex))

complex128


array([0.+1.j, 0.+0.j, 1.+0.j])

#### Real and Imaginary Parts

In [7]:
data = np.array([1, 2, 3], dtype=complex)
print(data)
print(data.real, data.imag)

[1.+0.j 2.+0.j 3.+0.j]
[1. 2. 3.] [0. 0. 0.]


#### Creating Arrays

In [8]:
data = np.array([1, 2, 3])
print(data.ndim)
print(data.shape)

# create two dimensional arrays with same data
data = np.array([[1, 2], [3, 4]])
print(data)
print(data.ndim)
print(data.shape)

1
(3,)
[[1 2]
 [3 4]]
2
(2, 2)


* **Arrays Filled with Constants**

In [9]:
data = np.zeros((2, 3))
print(data)

data = np.ones((2, 3))
print(data)

data = np.ones(4)
print(data)
print(data.dtype)
data = np.ones(4, dtype=np.int64)
print(data)
print(data.dtype)

x1 = 5.4 * np.ones(10)
print(x1)
x2 = np.full(10, 5.4)
print(x2)

x1 = np.empty(5)
print(x1)
x1.fill(3.0)
print(x1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1.]
float64
[1 1 1 1]
int64
[5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4]
[5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4]
[7.33943163e-317 0.00000000e+000 9.57228078e-317 1.34448306e-316
 2.37151510e-322]
[3. 3. 3. 3. 3.]


* **Arrays Filled with Incremental Sequences**

In [10]:
data = np.arange(0, 10, 1)
print(data)
data = np.linspace(0, 1, 10)
print(data)

[0 1 2 3 4 5 6 7 8 9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


* **Arrays Filled with Logarithm Sequences**

In [11]:
data = np.logspace(0, 2, 5) # 10**0 = 1 until 10**2 = 100
print(data)

[  1.           3.16227766  10.          31.6227766  100.        ]


* **Meshgrid Arrays**

In [12]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
print(">>", X)
print(">>", Y)

# a common use case of two dimensional coordinate arrays, like X and Y in this example, is to evaluate functions over two
# variables x and y.

Z = (X + Y) ** 2
print(">>", Z)

>> [[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
>> [[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]
>> [[9 4 1]
 [1 0 1]
 [1 4 9]]


* **Creating Uninitialized Arrays**

In [13]:
print(np.empty(3, dtype=float))

[1. 2. 3.]


* **Creating Arrays with Properties of other Arrays**

In [14]:
def f(x):
    y = np.ones_like(x)
    return y

data = f(np.array([1, 2, 3], dtype=float))
print(data)
print(data.dtype)

[1. 1. 1.]
float64


* **Creating Matrix Arrays**

In [15]:
data = np.identity(4)
print(data)

data = np.eye(3, k=-1)
print(data)

print(np.diag(np.arange(0, 20, 5)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


#### Indexing Slices

* **One Dimensional Arrays**

In [16]:
data = np.arange(1, 20, 1)
print(data[0])

print(data[-1])
print(data[5:9])
print(data[1::2])
print(data[::-1])

1
19
[6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


* **Multidimensional Arrays**

In [17]:
data = np.reshape(np.arange(0, 25), (5, 5))
print(data)
print(data[:, 0])
print(data[0::2, 0])
print(data[:, ::2])
print(data[:3, :3])
print(data[data > 5]) # using fance indexing
print(data[:, [0, 4]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  5 10 15 20]
[ 0 10 20]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 0  4]
 [ 5  9]
 [10 14]
 [15 19]
 [20 24]]


#### Views

In [18]:
data = np.ones((5, 5))
print(data)
b = data[:, ::2]
print(b)
b[:, :] = 0
print(b)
print(data)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]]


#### Reshaping and Resizing

In [27]:
data = np.array([[1, 2], [3, 4]])
print(data)
print("dims", data.shape)

data = np.reshape(data, 4);
print(data)
print("dims", data.shape)
data = np.reshape(data, (2, 2))
print(data)
print(data.flatten())
print(data)

data = np.arange(0, 5)
print(data)
column = data[:, np.newaxis]
print(column)

row = data[np.newaxis, :]
print(row)

column = np.expand_dims(data, axis=1)
print(column)
row = np.expand_dims(data, axis=0);
print(row)
np.vstack((data, data, data))
data = data[:, np.newaxis]
print(np.hstack((data, data, data)))

[[1 2]
 [3 4]]
dims (2, 2)
[1 2 3 4]
dims (4,)
[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


#### Aggregate Functions

In [41]:
data = np.random.normal(size=(15, 15))
np.mean(data)

data = np.arange(1, 10).reshape(3, 3)
print(data)

print(np.sum(data))
print(np.sum(data, axis=0).shape) # summation in axis 0 (row)
print(np.sum(data, axis=1).shape) # summation in axis 1 (column)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
(3,)
(3,)
